_wandb:
    value:
        cli_version: 0.22.2
        e:
            4n0t3dvw3mi210h1thrl49aowez0qebs:
                codePath: mpc/tests/clone_tora_dynamics.py
                codePathLocal: mpc/tests/clone_tora_dynamics.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "514908536832"
                        used: "131908526080"
                email: samakin@stanford.edu
                executable: /home/sam/miniconda3/envs/obstacle_avoidance_mpc/bin/python
                git:
                    commit: ceeb14b1d3a04933d7b6e13f600f2f50dff82338
                    remote: https://github.com/sakinwande/obstacle_avoidance_mpc
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-1e98a4f9-058f-d3e1-7956-b00a88e024bc
                host: sam-desktop
                memory:
                    total: "66512781312"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/sam/Documents/Code/obstacle_avoidance_mpc/mpc/tests/clone_tora_dynamics.py
                python: CPython 3.9.21
                root: /home/sam/Documents/Code/obstacle_avoidance_mpc
                startedAt: "2026-01-05T23:53:58.216515Z"
                writerId: 4n0t3dvw3mi210h1thrl49aowez0qebs
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
            "4": 3.9.21
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 128
hidden_layer_width:
    value: 200
hidden_layers:
    value: 2
lr:
    value: 0.001
n_epochs:
    value: 5000
n_pts:
    value: 80000
