_wandb:
    value:
        cli_version: 0.22.2
        e:
            j8g728ta7sw4gy9i5k5mocjjcrlil4oh:
                codePath: mpc/tests/clone_tora_dynamics.py
                codePathLocal: mpc/tests/clone_tora_dynamics.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "514908536832"
                        used: "131809054720"
                email: samakin@stanford.edu
                executable: /home/sam/miniconda3/envs/obstacle_avoidance_mpc/bin/python
                git:
                    commit: ceeb14b1d3a04933d7b6e13f600f2f50dff82338
                    remote: https://github.com/sakinwande/obstacle_avoidance_mpc
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-1e98a4f9-058f-d3e1-7956-b00a88e024bc
                host: sam-desktop
                memory:
                    total: "66512781312"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/sam/Documents/Code/obstacle_avoidance_mpc/mpc/tests/clone_tora_dynamics.py
                python: CPython 3.9.21
                root: /home/sam/Documents/Code/obstacle_avoidance_mpc
                startedAt: "2025-12-31T16:15:12.750606Z"
                writerId: j8g728ta7sw4gy9i5k5mocjjcrlil4oh
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
                - 61
            "4": 3.9.21
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 128
hidden_layer_width:
    value: 100
hidden_layers:
    value: 3
lr:
    value: 0.001
n_epochs:
    value: 20000
n_pts:
    value: 80000
